name: docker build and publish
on:
  push:
    branches:
      - master
jobs:
  build-and-publish:
    name: build and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: docker build
        run: docker build -t xinminlabs/synvert-playground:$GITHUB_SHA .
      - name: docker push
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p "${{ secrets.DOCKER_PASSWORD }}"
          docker push xinminlabs/synvert-playground:$GITHUB_SHA
